version: '3'

services:

  db:
    build: ./db
    restart: always
    ports:
     - 5432:5432
    volumes:
     - dbdata:/var/lib/postgresql/data
    networks:
     - store
    container_name: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
     - db
    networks:
     - store
    container_name: adminer
  
  server:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - store
    container_name: server

volumes:
  dbdata:
    
networks:
  store:
      driver: bridge